// uiActionTypes.js
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const DISPLAY_NOTIFICATION_DRAWER = "DISPLAY_NOTIFICATION_DRAWER";
export const HIDE_NOTIFICATION_DRAWER = "HIDE_NOTIFICATION_DRAWER";
// actionTypes.js
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
